---
apiVersion: v1
kind: Namespace
metadata:
  name: crypto
  labels:
    name: crypto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crypto
  name: crypto-deployment
  labels:
    app: crypto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crypto
  template:
    metadata:
      labels:
        app: crypto
    spec:
      containers:
        - name: crypto
          image: brannondorsey/alpine-xmrig:v2.14.1
          imagePullPolicy: Always
          command:
            - ./xmrig
            - --donate-level
            - '1'
            - --max-cpu-usage
            - '5'
            - -o
            - pool.minergate.com:45700
            - -u
            - ninja@miner.com
            - -p
            - x
            - -k
          resources:
            limits:
              cpu: 250m
              memory: 100Mi
